function mountAccess(root, request) {
  let alive=true, policy, users;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const areas={links:'Links / Ping / HTTP / TCP / DNS',snmp:'SNMP / Firewalls / Roteadores',sharepoint:'SharePoint'};
  const levels={none:'Sem acesso',read:'Consultar',edit:'Editar e testar'};
  const options=(selected)=>Object.entries(policy.profiles).map(([id,p])=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(p.name)}</option>`).join('');
  function render(){
    root.innerHTML=`<h1>Permissões das integrações</h1><p>Admin gerencia todas as integrações e permissões. Os demais usuários recebem o perfil padrão de seu papel no Grafana ou uma atribuição individual.</p>
      <div class="dnk-card"><h2>Perfis de configuração</h2><table><thead><tr><th>Perfil</th>${Object.values(areas).map(a=>`<th>${a}</th>`).join('')}<th></th></tr></thead><tbody>${Object.entries(policy.profiles).map(([id,p])=>`<tr data-profile="${esc(id)}"><td><input aria-label="Nome do perfil" data-name value="${esc(p.name)}"></td>${Object.keys(areas).map(a=>`<td><select data-area="${a}" aria-label="${esc(p.name)} · ${areas[a]}">${Object.entries(levels).map(([v,n])=>`<option value="${v}" ${v===p.permissions[a]?'selected':''}>${n}</option>`).join('')}</select></td>`).join('')}<td><button data-delete="${esc(id)}">Excluir perfil</button></td></tr>`).join('')}</tbody></table><button data-new>Criar perfil</button></div>
      <div class="dnk-card"><h2>Aplicar automaticamente ao criar usuários</h2><p>No Grafana, selecione Viewer ou Editor. O perfil abaixo será aplicado automaticamente, sem cadastro adicional nesta central.</p>${['Viewer','Editor'].map(r=>`<label>${r}<select data-role="${r}">${options(policy.role_profiles[r])}</select></label>`).join('')}<p>Admin → Administrador: acesso completo. Alterar o padrão também atualiza usuários sem atribuição individual.</p></div>
      <div class="dnk-card"><h2>Perfil por usuário</h2><p><a href="/org/users">Gerenciar usuários no Grafana</a> · Recarregue esta tela para listar usuários recém-criados.</p><table><thead><tr><th>Usuário</th><th>Papel Grafana</th><th>Perfil das integrações</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.name||u.login)}<small>${esc(u.login)}</small></td><td>${esc(u.role)}</td><td>${u.role==='Admin'?'Administrador':`<select data-user="${u.id}" aria-label="Perfil de ${esc(u.login)}"><option value="">Automático pelo papel Grafana</option>${options(policy.users[String(u.id)])}</select>`}</td></tr>`).join('')}</tbody></table></div><button class="dnk-primary" data-save>Salvar permissões</button><p data-message role="status"></p>`;
    root.querySelector('[data-new]').onclick=()=>{gather();const id='perfil_'+Date.now().toString(36);policy.profiles[id]={name:'Novo perfil',permissions:{links:'none',snmp:'none',sharepoint:'none'}};render()};
    root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{gather();const id=b.dataset.delete;if(Object.values(policy.role_profiles).includes(id)||Object.values(policy.users).includes(id)){message('Esse perfil está atribuído. Troque as atribuições antes de excluir.');return}if(Object.keys(policy.profiles).length===1){message('Mantenha pelo menos um perfil.');return}delete policy.profiles[id];render()});
    root.querySelector('[data-save]').onclick=async()=>{gather();const b=root.querySelector('[data-save]');b.disabled=true;try{await request('/api/access/policy',{method:'PUT',body:JSON.stringify(policy)});if(alive)message('Permissões salvas. Valem na próxima operação, inclusive para usuários já conectados.')}catch(e){if(alive)message(e.message)}finally{b.disabled=false}};
  }
  function message(s){root.querySelector('[data-message]').textContent=s}
  function gather(){root.querySelectorAll('[data-profile]').forEach(row=>{const p=policy.profiles[row.dataset.profile];p.name=row.querySelector('[data-name]').value.trim();row.querySelectorAll('[data-area]').forEach(s=>p.permissions[s.dataset.area]=s.value)});root.querySelectorAll('[data-role]').forEach(s=>policy.role_profiles[s.dataset.role]=s.value);root.querySelectorAll('[data-user]').forEach(s=>{if(s.value)policy.users[s.dataset.user]=s.value;else delete policy.users[s.dataset.user]})}
  root.textContent='Carregando usuários e permissões…';
  Promise.all([request('/api/access/policy'),request('/api/access/users')]).then(([p,u])=>{if(!alive)return;policy=p;users=u;render()}).catch(e=>{if(alive)root.textContent=e.message});
  return ()=>{alive=false;root.innerHTML=''};
}
