function mountAccess(host, request) {
  const root=host.attachShadow({mode:"open"});
  let alive=true, policy, users;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const areas={links:'Links / Ping / HTTP / TCP / DNS',snmp:'SNMP / Firewalls / Roteadores',sharepoint:'SharePoint',servidores:'Servidores / Alloy'};
  const levels={none:'Sem acesso',read:'Consultar',edit:'Editar e testar'};
  const options=(selected)=>Object.entries(policy.profiles).map(([id,p])=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(p.name)}</option>`).join('');
  function render(){
    root.innerHTML=`<style>
:host{display:block;min-width:0;color:var(--dnk-fg,#172b4d);font:15px/1.5 'Segoe UI',sans-serif}
*,*::before,*::after{box-sizing:border-box}h1{font-size:24px;line-height:1.3;margin:0 0 12px}h2{font-size:20px;line-height:1.4;margin:0 0 14px}p{margin:8px 0 18px}h1,h2,p,label{overflow-wrap:anywhere}
.dnk-card{background:var(--dnk-card,#fff);border:1px solid var(--dnk-line,#ced9e9);border-radius:10px;padding:clamp(16px,2vw,24px);margin-bottom:20px;min-width:0}
.profile{border:1px solid var(--dnk-line,#ced9e9);border-radius:8px;padding:16px;margin-bottom:16px}.profile-head{display:flex;align-items:end;gap:16px;flex-wrap:wrap;margin-bottom:16px}.profile-head label{flex:1;min-width:min(100%,220px)}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));gap:16px;align-items:start}.grid label{display:grid;grid-template-rows:minmax(44px,auto) 48px}label{display:flex;flex-direction:column;gap:8px;font-weight:600;min-width:0}
input,select{display:block;width:100%;max-width:100%;min-width:0;height:48px;padding:10px 12px;border:1px solid var(--dnk-line,#ced9e9);border-radius:7px;background:var(--dnk-input,#fff);color:var(--dnk-fg,#172b4d);font:400 16px/1.5 'Segoe UI',sans-serif;opacity:1}
select{appearance:auto;text-indent:0;-webkit-text-fill-color:var(--dnk-fg,#172b4d);color-scheme:normal}option{background:var(--dnk-input,#fff);color:var(--dnk-fg,#172b4d);font:400 16px/1.5 'Segoe UI',sans-serif}
button{min-height:44px;padding:10px 16px;border:1px solid var(--dnk-line,#ced9e9);border-radius:7px;background:var(--dnk-input,#e7eef9);color:var(--dnk-fg,#172b4d);font:600 15px/1.4 'Segoe UI',sans-serif;cursor:pointer;white-space:normal}button:disabled{opacity:.6}.dnk-primary{background:#2869d8;border-color:#2869d8;color:#fff}
.user{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,2fr);gap:16px;padding:16px 0;border-bottom:1px solid var(--dnk-line,#ced9e9);align-items:center}.user:last-child{border:0}small{display:block;color:var(--dnk-muted,#536782);overflow-wrap:anywhere}a{color:#4088ec}input:focus-visible,select:focus-visible,button:focus-visible{outline:2px solid #4088ec;outline-offset:2px}
@media(max-width:640px){.user{grid-template-columns:1fr}.profile-head button{width:100%}}
</style><h1>Permissões das integrações</h1><p>Admin gerencia todas as integrações e permissões. Os demais usuários recebem o perfil padrão de seu papel no Grafana ou uma atribuição individual.</p>
      <div class="dnk-card"><h2>Perfis de configuração</h2>${Object.entries(policy.profiles).map(([id,p])=>`<section class="profile" data-profile="${esc(id)}"><div class="profile-head"><label>Nome do perfil<input aria-label="Nome do perfil" data-name value="${esc(p.name)}"></label><button data-delete="${esc(id)}">Excluir perfil</button></div><div class="grid">${Object.entries(areas).map(([a,n])=>`<label>${n}<select data-area="${a}" aria-label="${esc(p.name)} · ${n}">${Object.entries(levels).map(([v,n])=>`<option value="${v}" ${v===p.permissions[a]?'selected':''}>${n}</option>`).join('')}</select></label>`).join('')}</div></section>`).join('')}<button data-new>Criar perfil</button></div>
      <div class="dnk-card"><h2>Aplicar automaticamente ao criar usuários</h2><p>No Grafana, selecione Viewer ou Editor. O perfil abaixo será aplicado automaticamente, sem cadastro adicional nesta central.</p><div class="grid">${['Viewer','Editor'].map(r=>`<label>${r}<select data-role="${r}">${options(policy.role_profiles[r])}</select></label>`).join('')}</div><p>Admin → Administrador: acesso completo. Alterar o padrão também atualiza usuários sem atribuição individual.</p></div>
      <div class="dnk-card"><h2>Perfil por usuário</h2><p><a href="/org/users">Gerenciar usuários no Grafana</a> · Recarregue esta tela para listar usuários recém-criados.</p>${users.map(u=>`<div class="user"><div><strong>${esc(u.name||u.login)}</strong><small>${esc(u.login)} · ${esc(u.role)}</small></div><label>Perfil das integrações${u.role==='Admin'?'<span>Administrador</span>':`<select data-user="${u.id}" aria-label="Perfil de ${esc(u.login)}"><option value="">Automático pelo papel Grafana</option>${options(policy.users[String(u.id)])}</select>`}</label></div>`).join('')||'<p>Nenhum usuário encontrado.</p>'}</div><button class="dnk-primary" data-save>Salvar permissões</button><p data-message role="status"></p>`;
    root.querySelector('[data-new]').onclick=()=>{gather();const id='perfil_'+Date.now().toString(36);policy.profiles[id]={name:'Novo perfil',permissions:{links:'none',snmp:'none',sharepoint:'none',servidores:'none'}};render()};
    root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{gather();const id=b.dataset.delete;if(Object.values(policy.role_profiles).includes(id)||Object.values(policy.users).includes(id)){message('Esse perfil está atribuído. Troque as atribuições antes de excluir.');return}if(Object.keys(policy.profiles).length===1){message('Mantenha pelo menos um perfil.');return}delete policy.profiles[id];render()});
    root.querySelector('[data-save]').onclick=async()=>{gather();const b=root.querySelector('[data-save]');b.disabled=true;try{await request('/api/access/policy',{method:'PUT',body:JSON.stringify(policy)});if(alive)message('Permissões salvas. Valem na próxima operação, inclusive para usuários já conectados.')}catch(e){if(alive)message(e.message)}finally{b.disabled=false}};
  }
  function message(s){root.querySelector('[data-message]').textContent=s}
  function gather(){root.querySelectorAll('[data-profile]').forEach(row=>{const p=policy.profiles[row.dataset.profile];p.name=row.querySelector('[data-name]').value.trim();row.querySelectorAll('[data-area]').forEach(s=>p.permissions[s.dataset.area]=s.value)});root.querySelectorAll('[data-role]').forEach(s=>policy.role_profiles[s.dataset.role]=s.value);root.querySelectorAll('[data-user]').forEach(s=>{if(s.value)policy.users[s.dataset.user]=s.value;else delete policy.users[s.dataset.user]})}
  root.textContent='Carregando usuários e permissões…';
  Promise.all([request('/api/access/policy'),request('/api/access/users')]).then(([p,u])=>{if(!alive)return;policy=p;users=u;render()}).catch(e=>{if(alive)root.textContent=e.message});
  return ()=>{alive=false;root.innerHTML=''};
}
