function mountOperations(host,request,area,me){
 const root=host.attachShadow({mode:'open'});
 let alive=true,state={assets:[],domains:[]};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={links:'Links',firewalls:'Firewalls e Roteadores',servidores:'Servidores',sharepoint:'SharePoint'};
 const colors=['#299c46','#8e959f','#f2cc0c','#e02f44','#a64dd8','#000'];
 const allowed=k=>me.permissions[k==='firewalls'?'snmp':k]!=='none';
 const edit=k=>me.permissions[k==='firewalls'?'snmp':k]==='edit';
 const download=(value,file,type='application/json')=>{const url=URL.createObjectURL(new Blob([typeof value==='string'||value instanceof Uint8Array?value:JSON.stringify(value,null,2)],{type}));const a=document.createElement('a');a.href=url;a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const downloadBundle=r=>{if(!r.bundle_base64)throw Error('Pacote do agente não disponível. Atualize a central.');const bytes=Uint8Array.from(atob(r.bundle_base64),c=>c.charCodeAt(0));download(bytes,r.bundle_name,'application/zip')};
 const message=text=>{if(alive)root.querySelector('[data-msg]').textContent=text};
 const css=`<style>
:host{display:block;color:var(--dnk-fg,#172b4d);font:14px/1.5 'Segoe UI',sans-serif;min-width:0}
*,*::before,*::after{box-sizing:border-box}
.dnk-card{padding:clamp(16px,2vw,24px);border:1px solid var(--dnk-line,#ced9e9);border-radius:10px;background:var(--dnk-card,#fff);width:100%;min-width:0}
h2{font-size:22px;line-height:1.3;margin:0 0 12px;overflow-wrap:anywhere}h3{font-size:18px;margin:16px 0 10px}p{margin:8px 0 16px;overflow-wrap:anywhere}
.ops-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,220px),1fr));gap:16px;margin:16px 0;align-items:start}
label{display:flex;flex-direction:column;gap:7px;min-width:0;margin:0;font-weight:600;line-height:1.4;overflow-wrap:anywhere}
input:not([type=checkbox]),select,textarea{display:block;width:100%;min-width:0;max-width:100%;min-height:44px;margin:0;padding:10px 12px;border:1px solid var(--dnk-line,#ced9e9);border-radius:7px;background:var(--dnk-input,#fff);color:var(--dnk-fg,#172b4d);font:400 14px/1.5 'Segoe UI',sans-serif;opacity:1}
select{appearance:auto;text-indent:0;-webkit-text-fill-color:var(--dnk-fg,#172b4d);height:44px;color-scheme:normal}
option{background:var(--dnk-input,#fff);color:var(--dnk-fg,#172b4d);font:400 14px/1.5 'Segoe UI',sans-serif}
textarea{min-height:280px;resize:vertical;white-space:pre;overflow:auto;font-family:Consolas,monospace}
.ops-checks label{flex-direction:row;align-items:center;font-weight:400;gap:10px}.ops-checks input[type=checkbox]{flex:none;width:17px;height:17px;margin:0;accent-color:#4088ec}
button,.ops-button{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:40px;max-width:100%;padding:9px 13px;border:1px solid var(--dnk-line,#ced9e9);border-radius:7px;background:var(--dnk-input,#e7eef9);color:var(--dnk-fg,#172b4d);font:600 14px/1.35 'Segoe UI',sans-serif;cursor:pointer;text-decoration:none;white-space:normal;overflow-wrap:anywhere}
button:disabled{opacity:.6;cursor:wait}.dnk-primary{background:#2869d8;border-color:#2869d8;color:#fff}.ops-actions{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0}.ops-button:hover{border-color:#4088ec}
input:focus-visible,select:focus-visible,button:focus-visible,a:focus-visible{outline:2px solid #4088ec;outline-offset:2px}
pre{white-space:pre-wrap;max-height:400px;overflow:auto}.badge{display:inline-block;border-radius:5px;padding:4px 10px;color:white}
table{width:100%;border-collapse:collapse}td,th{padding:10px;text-align:left;vertical-align:top;border-bottom:1px solid var(--dnk-line,#ced9e9);overflow-wrap:anywhere}small{display:block}.ops-table{overflow:auto}.help{color:var(--dnk-muted,#536782);font-size:13px}[hidden]{display:none!important}
@media(max-width:600px){.ops-grid{grid-template-columns:1fr}.ops-actions>*{width:100%}}
</style>`;
 if(area==='alloy'){
 const canEdit=me.permissions.servidores==='edit';
 const labels={cpu:'Processamento',memory:'Memória RAM',disk:'Disco',network:'Rede',services:'Serviços',logs:'Logs de eventos'};
 let agents=[],loading=null;
 root.innerHTML=css+`<style>.agent-list{display:grid;gap:16px}.agent{padding:18px;border:1px solid var(--dnk-line,#ced9e9);border-radius:8px;min-width:0}.agent-head{display:flex;justify-content:space-between;align-items:start;gap:16px;flex-wrap:wrap}.agent h3{margin:0;font-size:18px;overflow-wrap:anywhere}.agent p{margin:8px 0}.agent small{color:var(--dnk-muted,#536782)}.agent .ops-actions{margin-bottom:0}.ops-editor{margin-top:24px;padding-top:24px;border-top:1px solid var(--dnk-line,#ced9e9)}</style><div class="dnk-card"><h2>Agentes Grafana Alloy</h2><p>Consulte os agentes cadastrados por cliente e unidade. Um novo cadastro aparece aqui imediatamente, mesmo antes de enviar dados.</p><div class="ops-actions"><button data-new class="dnk-primary">Novo agente</button><button data-reload>Atualizar lista</button><a class="ops-button" href="https://github.com/grafana/alloy/releases/latest" target="_blank" rel="noopener noreferrer">Baixar Alloy oficial · Windows</a><a class="ops-button" href="https://grafana.com/docs/alloy/latest/set-up/install/linux/" target="_blank" rel="noopener noreferrer">Instalar Alloy · Linux</a></div><label>Buscar por cliente, unidade ou servidor<input data-search type="search" placeholder="Digite para filtrar os agentes"></label><p data-count class="help"></p><p data-msg role="status"></p><div data-list class="agent-list"></div><section data-editor class="ops-editor" hidden><h3>Novo agente</h3><p>Escolha a coleta. A configuração conecta os exportadores e os destinos automaticamente e cadastra o servidor no inventário.</p><form data-form><div class="ops-grid"><label>CLIENTE<input name="CLIENTE" required maxlength="120"></label><label>UNIDADE<input name="UNIDADE" required maxlength="120"></label><label>Nome do servidor<input name="instance" required pattern="[A-Za-z0-9_.-]+"></label><label>Sistema<select name="os"><option value="windows">Windows</option><option value="linux">Linux</option></select></label></div><div class="ops-grid ops-checks">${Object.entries(labels).map(([id,label])=>`<label><input type="checkbox" name="items" value="${id}" ${id==='logs'||id==='services'?'':'checked'}>${label}</label>`).join('')}</div><div class="ops-actions"><button class="dnk-primary" type="submit">Gerar e cadastrar servidor</button><button type="button" data-cancel>Fechar cadastro</button></div></form><div data-result hidden><h3>Configuração gerada</h3><textarea data-config readonly aria-label="Configuração Alloy"></textarea><p data-instructions></p><div class="ops-actions"><button data-package class="dnk-primary">Baixar agente com config (ZIP)</button><button data-download>Baixar somente config.alloy</button></div><p class="help">No Windows, o ZIP contém um script que baixa o instalador oficial e aplica a config. Extraia no servidor e execute como Administrador. A senha de ingestão será solicitada na execução.</p></div></section></div>`;
 function renderAgents(){
 if(!alive)return;
 const q=root.querySelector('[data-search]').value.trim().toLocaleLowerCase('pt-BR');
 const rows=agents.filter(a=>[a.CLIENTE,a.UNIDADE,a.name,a.instance,a.tipo].some(v=>String(v||'').toLocaleLowerCase('pt-BR').includes(q)));
 root.querySelector('[data-count]').textContent=rows.length+' de '+agents.length+' agente(s) · '+agents.filter(a=>a.enabled).length+' ativo(s) · '+agents.filter(a=>!a.enabled).length+' pausado(s)';
 root.querySelector('[data-list]').innerHTML=rows.map(a=>`<article class="agent"><div class="agent-head"><div><h3>${esc(a.name||a.instance)}</h3><small>CLIENTE: ${esc(a.CLIENTE)} · UNIDADE: ${esc(a.UNIDADE)}</small></div><span class="badge" style="background:${colors[a.status]};color:${[1,2].includes(a.status)?'#101823':'#fff'}">${esc(a.status_name)}</span></div><p>${a.tipo==='windows'?'Windows':'Linux'} · ${esc(a.instance)}</p><p><strong>Coleta:</strong> ${esc((a.items||[]).map(i=>labels[i]||i).join(', ')||'Configuração existente')}</p><p class="help">${esc(a.reason)}</p>${canEdit?`<div class="ops-actions"><button data-existing-package="${esc(a.id)}">Baixar agente com config</button><button data-pause="${esc(a.id)}" data-enabled="${!a.enabled}">${a.enabled?'Pausar':'Ativar'}</button><button data-delete="${esc(a.id)}">Excluir</button></div>`:''}</article>`).join('')||`<p>${agents.length?'Nenhum agente corresponde à busca.':'Nenhum agente cadastrado. Clique em Novo agente para criar o primeiro.'}</p>`;
 }
 async function loadAgents(){while(loading)await loading;if(!alive)return;const pending=(async()=>{try{const rows=await request('/api/alloy/agents');if(!alive)return;agents=rows;renderAgents()}catch(e){message('Não foi possível atualizar a lista: '+e.message)}})();loading=pending;try{await pending}finally{loading=null}}
 root.querySelector('[data-new]').hidden=!canEdit;
 root.querySelector('[data-form]').querySelectorAll('input,select,button').forEach(x=>{if(!canEdit)x.disabled=true});
 root.querySelector('[data-search]').oninput=renderAgents;
 root.querySelector('[data-reload]').onclick=loadAgents;
 root.querySelector('[data-new]').onclick=()=>{root.querySelector('[data-editor]').hidden=false;root.querySelector('[data-form]').reset();root.querySelector('[data-result]').hidden=true;root.querySelector('[data-form]').elements.CLIENTE.focus()};
 root.querySelector('[data-cancel]').onclick=()=>{root.querySelector('[data-editor]').hidden=true};
 root.querySelector('[data-form]').onsubmit=async e=>{e.preventDefault();if(!canEdit){message('Seu perfil permite apenas consulta.');return}const f=e.target,b=f.querySelector('[type=submit]');b.disabled=true;try{const value={CLIENTE:f.elements.CLIENTE.value,UNIDADE:f.elements.UNIDADE.value,instance:f.elements.instance.value,os:f.elements.os.value,items:[...f.querySelectorAll('[name=items]:checked')].map(x=>x.value)};const r=await request('/api/alloy',{method:'POST',body:JSON.stringify(value)});if(!alive)return;root.querySelector('[data-config]').value=r.config;root.querySelector('[data-instructions]').textContent=r.instructions;root.querySelector('[data-result]').hidden=false;root.querySelector('[data-download]').onclick=()=>download(r.config,'config.alloy','text/plain');root.querySelector('[data-package]').onclick=()=>{try{downloadBundle(r)}catch(e){message(e.message)}};await loadAgents();message('Servidor cadastrado e listado. Sem Dados até o agente começar a enviar.')}catch(e){message(e.message)}finally{b.disabled=false}};
 root.querySelector('[data-list]').onclick=async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;b.disabled=true;try{
 if(b.dataset.existingPackage){const r=await request('/api/alloy/package/'+b.dataset.existingPackage,{method:'POST',body:'{}'});if(alive){downloadBundle(r);message('Pacote baixado com o mesmo ID do agente cadastrado.')}}
 if(b.dataset.pause||b.dataset.delete){const id=b.dataset.pause||b.dataset.delete;if(b.dataset.delete&&!confirm('Mover agente para Itens Excluídos? O cadastro e histórico serão preservados.'))return;await request('/api/servers/servidores/'+id,{method:'POST',body:JSON.stringify(b.dataset.delete?{delete:true}:{enabled:b.dataset.enabled==='true'})});await loadAgents();message(b.dataset.delete?'Agente movido para Itens Excluídos.':b.dataset.enabled==='true'?'Agente ativado.':'Agente pausado.')}
 }catch(e){message(e.message)}finally{b.disabled=false}};
 loadAgents();const timer=setInterval(loadAgents,30000);
 return ()=>{alive=false;clearInterval(timer);root.innerHTML=''};
 }
 root.innerHTML=css+`<div class="dnk-card"><h2>${area==='excluidos'?'Itens Excluídos':area==='dominios'?'Domínios e Certificados':'Servidores e Histórico'}</h2><p>${area==='excluidos'?'Exclusões preservam identificadores, configurações, credenciais e histórico. Reative para voltar à coleta.':area==='dominios'?'Consulta online a cada 5 minutos. Configure os destinos e o acesso em config/global/domains.json.':'Estado atual, motivos e exportação de dados por integração.'}</p><button data-reload>Atualizar</button><p data-msg role="status"></p><div data-list></div></div>`;
 async function load(){
 try{
 if(area==='dominios'){const r=await request('/api/global/status');if(!alive)return;root.querySelector('[data-list]').innerHTML=`<p>Credenciais: <code>${esc(r.credentials_file)}</code> · Domínios: <code>${esc(r.domains_file)}</code></p><div class="ops-table"><table><thead><tr><th>Nome / destino</th><th>Status</th><th>Expiração</th><th>Última consulta</th></tr></thead><tbody>${r.domains.map(d=>`<tr><td>${esc(d.name)}<small>${esc(d.host)}:${d.port}</small></td><td><span class="badge" style="background:${colors[d.status]};color:${[1,2].includes(d.status)?'#101823':'#fff'}">${['OK','Sem Dados','Atenção','Grave','Crítico','Pausado'][d.status]}</span><small>${esc(d.error||'')}</small></td><td>${d.days_remaining!=null?Math.floor(d.days_remaining)+' dias':'—'}</td><td>${new Date(d.checked_at*1000).toLocaleString('pt-BR')}</td></tr>`).join('')}</tbody></table></div>`;return}
 if(area==='excluidos'){
 const entries=await Promise.all(Object.keys(names).filter(allowed).map(async k=>[k,await request(k==='sharepoint'?'/api/sharepoint/deleted':'/api/deleted/'+k)]));
 if(!alive)return;root.querySelector('[data-list]').innerHTML=entries.map(([k,rows])=>`<section><h3>${names[k]}</h3><button data-export="${k}">Baixar dados e histórico</button><div class="ops-table"><table><thead><tr><th>CLIENTE / UNIDADE</th><th>Ativo</th><th>Excluído em</th><th>Ações</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.CLIENTE)} / ${esc(r.UNIDADE)}</td><td>${esc(r.name)}<small>${esc(r.instance||r.tenant_id)}</small></td><td>${new Date(r.deleted_at*1000).toLocaleString('pt-BR')}</td><td>${edit(k)?`<button data-restore="${k}" data-id="${esc(r.id)}">Reativar</button>`:''}${k==='sharepoint'?`<button data-sp-export="${esc(r.id)}">CSV do histórico</button>`:''}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum item excluído.</td></tr>'}</tbody></table></div></section>`).join('');return}
 state=await request('/api/status');if(!alive)return;
 root.querySelector('[data-list]').innerHTML=`<p class="help">${esc(state.error||'Atualizado a cada 30 segundos.')} Última atualização: ${state.last_update?new Date(state.last_update*1000).toLocaleString('pt-BR'):'Aguardando'}</p>${Object.keys(names).filter(allowed).map(k=>`<section><h3>${names[k]}</h3><button data-export="${k}">Exportar dados e histórico</button><div class="ops-table"><table><thead><tr><th>CLIENTE / UNIDADE</th><th>Ativo</th><th>Status / diagnóstico</th><th>Ações</th></tr></thead><tbody>${state.assets.filter(a=>a.category===k).map(a=>`<tr><td>${esc(a.CLIENTE)} / ${esc(a.UNIDADE)}</td><td><a href="/d/dnk-${k}-detalhes?var-CLIENTE=${encodeURIComponent(a.CLIENTE)}&var-UNIDADE=${encodeURIComponent(a.UNIDADE)}&var-asset_id=${encodeURIComponent(a.asset_id)}">${esc(a.name)}</a></td><td><span class="badge" style="background:${colors[a.status]};color:${[1,2].includes(a.status)?'#101823':'#fff'}">${esc(a.status_name)}</span><small>${esc(a.reason)}</small></td><td>${k==='servidores'&&me.permissions.servidores==='edit'?`<button data-agent-package="${a.asset_id}">Baixar agente com config</button><button data-pause="${a.asset_id}" data-enabled="${a.status===5}">${a.status===5?'Ativar':'Pausar'}</button><button data-delete="${a.asset_id}">Excluir</button>`:''}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum ativo cadastrado.</td></tr>'}</tbody></table></div></section>`).join('')}`;
 }catch(e){message(e.message)}
 }
 root.onclick=async e=>{const b=e.target.closest('button');if(!b||b.dataset.reload!=null)return;if(b.disabled)return;b.disabled=true;
 try{
 if(b.dataset.agentPackage){const r=await request('/api/alloy/package/'+b.dataset.agentPackage,{method:'POST',body:'{}'});downloadBundle(r);message('Pacote baixado com o mesmo ID do servidor cadastrado.')}
 if(b.dataset.export){const k=b.dataset.export;const r=await request(k==='sharepoint'?'/api/sharepoint/history':'/api/history/'+k);download(r,'dunker-'+k+'-historico.json');message('Exportação concluída. O arquivo não contém credenciais.')}
 if(b.dataset.spExport)download(await request('/api/sharepoint/tenants/'+b.dataset.spExport+'/export',{},true),'sharepoint-'+b.dataset.spExport+'.csv','text/csv');
 if(b.dataset.restore){const k=b.dataset.restore;await request(k==='sharepoint'?'/api/sharepoint/restore/'+b.dataset.id:'/api/restore/'+k+'/'+b.dataset.id,{method:'POST',body:'{}'});message('Item reativado. Os dashboards atualizam na próxima coleta.');await load()}
 if(b.dataset.pause||b.dataset.delete){const id=b.dataset.pause||b.dataset.delete;if(b.dataset.delete&&!confirm('Mover servidor para Itens Excluídos?'))return;await request('/api/servers/servidores/'+id,{method:'POST',body:JSON.stringify(b.dataset.delete?{delete:true}:{enabled:b.dataset.enabled==='true'})});await load()}
 }catch(e){message(e.message)}finally{b.disabled=false}};
 root.querySelector('[data-reload]').onclick=load;load();const timer=setInterval(load,30000);
 return ()=>{alive=false;clearInterval(timer);root.innerHTML=''};
}
