apiVersion: 1
datasources:
- name: Prometheus Dunker
  uid: dnk-prometheus
  type: prometheus
  access: proxy
  url: $PROM_URL
  isDefault: true
  editable: false
  jsonData:
    timeInterval: 30s
    httpMethod: POST
- name: Loki Dunker
  uid: dnk-loki
  type: loki
  access: proxy
  url: $LOKI_URL
  editable: false
- name: Alertmanager Dunker
  uid: dnk-alertmanager
  type: alertmanager
  access: proxy
  url: $AM_URL
  editable: false
  jsonData:
    implementation: prometheus
