apiVersion: 1
datasources:
- name: SharePoint Dunker
  uid: dnk-sharepoint
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  editable: false
  jsonData:
    timeInterval: 30s
    httpMethod: POST
